ARG baseimage="debian:12"
ARG osname="debian-12"
FROM ${baseimage}

USER root
ENV DEVTOOLS_COMPUTER_ID=${osname}
ENV WRKDIR=/opt/repo
WORKDIR ${WRKDIR}

RUN \
    mkdir -p ${WRKDIR} ; \
    cd ${WRKDIR} ; \
    echo "+ cloning..." ; \
    git clone --depth=100 https://gitlab.pleiade.edf.fr/codeaster/src.git ; \
    echo "+ running configure..." ; \
    cd ${WRKDIR}/src ; \
    ./configure --prefix=/opt/codeaster ; \
    echo "+ compiling..." ; \
    jobs=$(( $(nproc) - 2 )) ; \
    make install -j ${jobs} ; \
    cd / ; \
    rm -rf ${WRKDIR}

ENV WRKDIR=

USER user
WORKDIR /home/user

ENTRYPOINT ["/opt/codeaster/bin/run_aster"]
