variables:
  ROOT_URL: https://$GITLAB_TOKEN_NAME:$GITLAB_TOKEN@gitlab.pleiade.edf.fr/codeaster
  PREREQ_VERSION: 20240327
  IMAGE_URL: nexus.retd.edf.fr:5075/codeaster-prerequisites:${PREREQ_VERSION}-debian-10
  BUILD: mpi
  REFREV: ${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}
  GIT_SSL_NO_VERIFY: "true"
  NPROC_MAX: 16
  reg_debugging: '/^debugci.*/'
  FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR: "true"

default:
  tags:
    - docker-executor

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "schedule"
      variables:
        IMAGE_URL: nexus.retd.edf.fr:5075/codeaster-prerequisites:${PREREQ_VERSION}-debian-11
    - if: $CI_COMMIT_REF_NAME =~ $reg_debugging
      variables:
        BUILD: debug

stages:
  - setup
  - build
  - test

image:
  name: ${IMAGE_URL}

prepare:
  stage: setup
  script:
    - .gitlabci/prepare.sh
  artifacts:
    paths:
      - devtools/*
      - data-src/*
    expire_in: 6 hours

compile:
  stage: build
  needs: ["prepare"]
  script:
    - .gitlabci/compile.sh
  artifacts:
    paths:
      - .lock*
      - build/mpi*/config.log
      - build/mpi*/c4che/*
      - build/mpi*/*/*.h
      - build/mpi*/*/*.py
      - build/mpi*/*/code_aster/*.py
      - build/mpi*/*/*/*.so
      - build/mpi*/*/catalo/elem.1
      - build/mpi*/*/*.mod
      - install/*
    expire_in: 3 days

doc_html:
  stage: build
  needs: ["prepare", "compile"]
  script:
    - .gitlabci/doc_html.sh
  artifacts:
    paths:
      - install/share/doc/html/*
    expire_in: 3 days
  rules:
    - if: $CI_MERGE_REQUEST_IID

minimal_build:
  stage: test
  needs: ["prepare", "compile", "check_source"]
  script:
    - .gitlabci/compile_minimal.sh
  rules:
    - if: $CI_MERGE_REQUEST_IID

check_source:
  stage: test
  needs: ["prepare", "compile"]
  script:
    - .gitlabci/check_source.sh
  artifacts:
    paths:
      - list_issues.txt
    expire_in: 3 days
  rules:
    - if: $CI_MERGE_REQUEST_IID

check_issues:
  stage: test
  needs: ["prepare", "check_source"]
  script:
    - .gitlabci/check_issues.sh
  rules:
    - if: $CI_MERGE_REQUEST_IID

minimal_test:
  stage: test
  needs: ["prepare", "compile"]
  script:
    - .gitlabci/test.sh
        -R "(asrun0|mumps02b|supv002|vocab0|zzzz509j)"
        --resutest=results_mini
  artifacts:
    when: always
    paths:
      - results_mini/run_testcases.xml
      - results_mini/Testing/Temporary/*
      - results_mini/*
    expire_in: 3 days
    reports:
      junit: results_mini/run_testcases.xml
  rules:
    - if: $CI_MERGE_REQUEST_IID

verification_test:
  stage: test
  tags:
    - hulk
  needs: ["prepare", "compile", "minimal_test", "check_source", "doc_html"]
  script:
    - .gitlabci/test.sh
        -L verification
        --only-failed-results
        --exclude-testlist .gitlabci/known_failures-pleiade.list
        --resutest=results
  artifacts:
    when: always
    paths:
      - results/run_testcases.xml
      - results/Testing/Temporary/*
      - results/*
    expire_in: 3 days
    reports:
      junit: results/run_testcases.xml
  rules:
    - if: $CI_COMMIT_REF_NAME !~ $reg_debugging

known_failures_test:
  stage: test
  needs: ["prepare", "compile", "minimal_test"]
  script:
    - .gitlabci/test.sh
        --testlist .gitlabci/known_failures-pleiade.list
        --resutest=results_failures
  allow_failure: true
  artifacts:
    when: always
    paths:
      - results_failures/run_testcases.xml
      - results_failures/Testing/Temporary/*
      - results_failures/*
    expire_in: 3 days
    reports:
      junit: results_failures/run_testcases.xml
  rules:
    - if: $CI_MERGE_REQUEST_IID

debugging_test:
  stage: test
  needs: ["prepare", "compile"]
  script:
    - .gitlabci/test.sh
        --testlist .gitlabci/debugging.list
        --resutest=results_debugging
  allow_failure: true
  artifacts:
    when: always
    paths:
      - results_debugging/run_testcases.xml
      - results_debugging/Testing/Temporary/*
      - results_debugging/*
    expire_in: 3 days
    reports:
      junit: results_debugging/run_testcases.xml
  rules:
    - if: $CI_COMMIT_REF_NAME =~ $reg_debugging
