
c_stdlib:
  - if: win
    then: vs
  - if: linux
    then: sysroot

c_stdlib_version:
  - if: linux
    then: 2.17
  - if: win
    then: 2022

c_compiler:
  - if: win
    then: vs2022
  - if: linux
    then: gcc

cxx_compiler:
  - if: win
    then: vs2022
  - if: linux
    then: gxx

fortran_compiler:
  - if: linux
    then: gfortran
  - if: win
    then: flang

c_compiler_version:
  - if: linux
    then: 13

cxx_compiler_version:
  - if: linux
    then: 13

fortran_compiler_version:
  - if: linux
    then: 13
  - if: win
    then: 18

libblas:
  - if: not win
    then: "3.9 *netlib"
  - if: win
    then: "3.9 *mkl"

liblapack:
  - if: not win
    then: "3.9 *netlib"
  - if: win
    then: "3.9 *mkl"

numpy:
  - 1.26

vc:
  - if: win
    then: 14

python:
  - 3.12

mpi_prefix:
  - nompi

clang:
  - 18
