name: codeaster-deps
channels:
  - conda-forge
dependencies:
  - python 3.11
  - mfront=4.2.0
  - mgis=2.2
  - libmed=4.1.1
  - medcoupling=9.12.0
  - scotch=7.0.4
  - metis=5.1.0
  - mumps-seq=5.6.2
  - sysroot_linux-64=2.17
  - waf
  - cmake
  - gdb
  - pyyaml
  - python-dotenv
  - gcc
  - gxx
  - gfortran
