name: codeaster-deps
dependencies:
  - python 3.11
  - mfront=4.2.0
  - hdf5=1.14.4.2
  - mgis=2.2
  - libmed=4.1.1
  - medcoupling=9.12.0
  - scotch=7.0.4
  - numpy=1.23
  - metis=5.1.0
  - mumps-seq=5.6.2
  - sysroot_linux-64=2.17
  - waf=2.0.27
  - cmake
  - gdb
  - pyyaml
  - python-dotenv
  - gcc=12
  - gxx=12
  - gfortran=12
