name: codeaster-deps
dependencies:
  - python 3.11.9
  - mfront=4.2.0
  - hdf5=1.14.4.2
  - mgis=2.2
  - libmed=4.1.1
  - medcoupling=9.12.0
  - scotch=7.0.4
  - numpy=1.23
  - metis=5.1.0=*aster*
  - mumps=5.6.2=*aster*
  - sysroot_linux-64=2.17
  - waf=2.0.27
  - openblas
  - cmake
  - gdb
  - pyyaml
  - python-dotenv
  - gcc=12
  - gxx=12
  - gfortran=12
