name: codeaster-deps
dependencies:
  - python 3.11.9
  - vswhere
  - libboost-devel=1.84
  - libblas=*=*netlib
  - liblapack=*=*netlib
  - mfront=4.2.0
  - mgis=2.2
  - mkl-devel=2024.1
  - libmed=4.1.1
  - medcoupling=9.12.0
  - scotch=7.0.4
  - metis=5.1.0
  - mumps=5.6.2
  - waf=2.0.27
  - numpy=1.23
  - pyyaml
  - python-dotenv
  - cmake
  - psutil
  - intel-fortran-rt=2024.1  # This was the root cause of the __atomic issues!
# It appears that it relies on llvm-openmp which overrides the intel-openmp package.
# However, we still need it for the fortran runtime. One can either re-compile mkl using the llvm-openmp package.
# Or try to compile intel-fortran-rt with the intel-openmp package.
# Temp fix is to do mamba remove llvm-openmp intel-openmp --force && mamba install intel-openmp
  - clang=18.1.6
#  - lld=18.1.6
#  - lldb=18.1.6
#  - pip
#  - pip:
#      - dlltracer