name: codeaster-deps-nomkl
channels:
  - conda-forge
dependencies:
  - python 3.12
  - vswhere
  - libblas
  - nomkl
  - mfront=4.2.0
  - mgis=2.2
  - libmed=4.1.1
  - medcoupling=9.10.0
  - scotch=7.0.4
  - metis=5.1.0
  - mumps-seq=5.6.2
  - waf
  - pyyaml
  - python-dotenv
  - clang 18.1.2
  - clangxx 18.1.2
  - lld 18.1.2
