name: codeaster-deps
channels:
  - conda-forge
dependencies:
  - python 3.11
  - vswhere
  - libblas=*=*mkl
  - mfront=4.2.0
  - mgis=2.2
  - mkl-devel
  - libmed=4.1.1
  - medcoupling=9.12.0
  - scotch=7.0.4
  - metis=5.1.0
#  - mumps-seq=5.6.2
  - waf=2.0.27
  - numpy=1.23
  - pyyaml
  - python-dotenv
  - intel-fortran-rt=2024.0
  - clang=18.1.3
  - clangxx=18.1.3
  - lld=18.1.3
  - pip
  - pip:
      - dlltracer