schema_version: 1

context:
  name: code-aster
  version: 17.1.16
  win_build: 2
  build: 200
  mpi_prefix: nompi
  build_type: debug

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - path: ..

build:
  number: ${{ build }}
  script:
    file: bld.bat
    env:
      build_type: ${{ build_type }}
  string: py${{ CONDA_PY }}_${{ mpi_prefix }}_${{ build_type }}_h${{ PKG_HASH }}_${{ build }}
  prefix_detection:
    ignore_binary_files: true


requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - if: not win
      then: ${{ compiler('fortran') }}
    - pyyaml
    - waf 2.0.27
    - if: win
      then: clang
    - setuptools
  host:
    - python
    - numpy
    - libboost-devel
    - if: win
      then: mkl-devel
    - if: not win
      then: openblas
    - libblas
    - liblapack
    - "metis * *debug*"
    - "mumps * *debug*"
    - "mfront * *debug*"
    - "mgis * *debug*"
    - "libmed * *debug*"
    - "scotch * *debug*"
    - "medcoupling * *debug*"
    - psutil
  run:
    - python
    - if: win
      then:
        - intel-fortran-rt
        - "libblas * *mkl"
        - "liblapack * *mkl"
    - ${{ pin_compatible('numpy', upper_bound='x.x') }}
    - if: not win
      then: libxcrypt
  run_exports:
    - ${{ pin_subpackage(name, upper_bound='x.x') }}
  ignore_run_exports:
    by_name:
      - llvm-openmp

tests:
  - python:
      imports:
        - code_aster
      pip_check: false

  - script:
      - run_ctest --resutest=temp\\seq -L submit -L sequential -LE need_data --timefactor=5.0 --only-failed-results
      - if errorlevel 1 exit 1
    files:
      source:
        - basic_import.py

about:
  license: GPL-3.0-only AND CECILL-C AND Apache-2.0 AND LGPL-3.0-only
  summary: Code_Aster - a finite element solver
  description: |
    Code_Aster offers a full range of multiphysical analysis and modelling methods that go well beyond the standard functions of a thermomechanical calculation code: from seismic analysis to porous media via acoustics, fatigue, stochastic dynamics, etc..
  homepage: https://www.code-aster.org
  repository: https://sourceforge.net/projects/codeaster/
  documentation: https://www.code-aster.org/V2/doc/default/en/index.php?man=commande

extra:
  recipe-maintainers:
    - Krande



