# coding=utf-8
# --------------------------------------------------------------------
# Copyright (C) 1991 - 2024 - EDF R&D - www.code-aster.org
# This file is part of code_aster.
#
# code_aster is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# code_aster is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with code_aster.  If not, see <http://www.gnu.org/licenses/>.
# --------------------------------------------------------------------

import os.path as osp
import pathlib
import sys

from waflib import Configure, TaskGen, Utils, Logs, Build


def options(self):
    self.load("compiler_c")
    group = self.get_option_group("code_aster options")
    group.add_option(
        "--msvc-entry",
        dest="msvc_entry",
        action="store_false",
        help="rewrites pybind11 entry points for MSVC to skip symlink",
    )


def configure(self):
    self.load("compiler_c")

    opts = self.options
    # preserve symbols in the dyn table for stdcallsspo
    if sys.platform == "darwin":
        # '--export-dynamic' is '-export_dynamic' in OS X linker
        # http://stackoverflow.com/questions/21279036/what-is-clangs-equivalent-to-rdynamic-gcc-flag
        self.env.append_unique("LINKFLAGS", ["-Wl,-export_dynamic"])
        # prefer memory usage over speed
        self.env.append_unique("LINKFLAGS", ["-Wl,--no-keep-memory"])
        self.env.append_unique("LINKFLAGS_LIBASTER", ["-Wl,--no-as-needed"])
    elif sys.platform == "win32":
        pass
    else:
        self.env.append_unique("LINKFLAGS", ["-Wl,--export-dynamic"])

        # prefer memory usage over speed
        self.env.append_unique("LINKFLAGS", ["-Wl,--no-keep-memory"])
        self.env.append_unique("LINKFLAGS_LIBASTER", ["-Wl,--no-as-needed"])

    incpath = osp.join(self.path.get_src().abspath(), "include")
    self.env.append_value("INCLUDES_BIBC", incpath)

    top_dir = pathlib.Path(self.path.get_bld().abspath()).parent.parent

    bibfor_incldir = osp.join(top_dir, "bibfor", "include")
    self.env.append_value("INCLUDES_BIBC", bibfor_incldir)

    bibcxx_incldir = osp.join(top_dir, "bibcxx", "include")
    self.env.append_value("INCLUDES_BIBC", bibcxx_incldir)

    if "ifort" in self.env.FC_NAME.lower():
        self.env.append_value("LINKFLAGS_fcprogram", ["-nofor-main"])
        if opts.embed_all or opts.embed_aster:
            self.env.append_value("LINKFLAGS_fcprogram", ["-static-intel"])
            if self.get_define("ASTER_HAVE_MPI"):
                self.env.append_value("LINKFLAGS_fcprogram", ["-static-mpi"])
    self.check_c_compiler_flags()


def build(self):
    env = self.all_envs[self.variant]
    use = ["BIBC"]

    # Build aster.pyd
    self(
        features="c cshlib",
        name=f"aster",
        source="c_entrypoints/entry_aster.c",
        target="aster_pyd",
        defines="",
        use=use,
        env=env.derive(),
        install_path=env.ASTERLIBDIR,
    )
