# coding=utf-8
# --------------------------------------------------------------------
# Copyright (C) 1991 - 2026 - EDF - www.code-aster.org
# This file is part of code_aster.
#
# code_aster is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# code_aster is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with code_aster.  If not, see <http://www.gnu.org/licenses/>.
# --------------------------------------------------------------------


from ..Commons import *
from ..Language.DataStructure import *
from ..Language.Syntax import *

AFFE_MODELE = OPER(
    nom="AFFE_MODELE",
    op=18,
    sd_prod=modele_sdaster,
    fr=tr("Définir le phénomène physique modélisé et le type d'éléments finis sur le maillage"),
    reentrant="n",
    regles=(AU_MOINS_UN("AFFE", "AFFE_SOUS_STRUC"),),
    MAILLAGE=SIMP(statut="o", typ=maillage_sdaster),
    INFO=SIMP(statut="f", typ="I", defaut=1, into=(1, 2)),
    #
    # ====
    # Définition des grandeurs caractéristiques
    # ====
    #
    GRANDEUR_CARA=FACT(
        statut="f",
        max=1,
        fr=tr("Grandeurs caractéristiques pour l'adimensionnement des indicateurs d'erreur HM"),
        #
        LONGUEUR=SIMP(statut="f", typ="R", val_min=0, fr=tr("Longueur caractéristique")),
        PRESSION=SIMP(statut="f", typ="R", val_min=0, fr=tr("Pression caractéristique")),
        TEMPERATURE=SIMP(statut="f", typ="R", val_min=0, fr=tr("Température caractéristique")),
    ),
    #
    AFFE_SOUS_STRUC=FACT(
        statut="f",
        regles=(UN_PARMI("TOUT", "SUPER_MAILLE"),),
        TOUT=SIMP(statut="f", typ="TXM", into=("OUI",)),
        SUPER_MAILLE=SIMP(statut="f", typ=ma, validators=NoRepeat(), max="**"),
        PHENOMENE=SIMP(statut="f", typ="TXM", defaut="MECANIQUE", into=("MECANIQUE",)),
    ),
    AFFE=FACT(
        statut="f",
        max="**",
        regles=(UN_PARMI("TOUT", "GROUP_MA")),
        TOUT=SIMP(statut="f", typ="TXM", into=("OUI",)),
        GROUP_MA=SIMP(statut="f", typ=grma, validators=NoRepeat(), max="**"),
        PHENOMENE=SIMP(statut="o", typ="TXM", into=("MECANIQUE", "THERMIQUE", "ACOUSTIQUE")),
        b_mecanique=BLOC(
            condition="""equal_to("PHENOMENE", 'MECANIQUE')""",
            fr=tr("modélisations mécaniques"),
            MODELISATION=SIMP(
                statut="o",
                typ="TXM",
                validators=NoRepeat(),
                max=1,
                into=(
                    "2D_DIS_T",
                    "2D_DIS_TR",
                    "2D_FLUI_ABSO",
                    "2D_FLUI_PESA",
                    "2D_FLUI_STRU",
                    "2D_FLUIDE",
                    "3D",
                    "3D_ABSO",
                    "3D_FAISCEAU",
                    "3D_FLUI_ABSO",
                    "3D_FLUIDE",
                    "3D_INCO_UPG",
                    "3D_INCO_UP",
                    "3D_INCO_UPO",
                    "3D_SI",
                    "3D_GRAD_VARI",
                    "3D_GRAD_INCO",
                    "3D_GVNO",
                    "3D_JOINT",
                    "3D_JOINT_HYME",
                    "3D_INTERFACE",
                    "3D_INTERFACE_S",
                    "AXIS",
                    "AXIS_FLUI_STRU",
                    "AXIS_FLUI_ABSO",
                    "AXIS_FLUIDE",
                    "AXIS_FOURIER",
                    "AXIS_INCO_UPG",
                    "AXIS_INCO_UP",
                    "AXIS_INCO_UPO",
                    "AXIS_SI",
                    "AXIS_GRAD_VARI",
                    "AXIS_GRAD_INCO",
                    "AXIS_GVNO",
                    "AXIS_JOINT",
                    "AXIS_INTERFACE",
                    "AXIS_INTERFACE_S",
                    "BARRE",
                    "CABLE_GAINE",
                    "2D_BARRE",
                    "C_PLAN",
                    "C_PLAN_SI",
                    "CABLE",
                    "CABLE_POULIE",
                    "COQUE_3D",
                    "COQUE_AXIS",
                    "D_PLAN",
                    "D_PLAN_GRAD_VARI",
                    "D_PLAN_GRAD_INCO",
                    "D_PLAN_GVNO",
                    "D_PLAN_GRAD_SIGM",
                    "PLAN_JOINT",
                    "PLAN_JOINT_HYME",
                    "PLAN_INTERFACE",
                    "PLAN_INTERFACE_S",
                    "D_PLAN_ABSO",
                    "D_PLAN_INCO_UPG",
                    "D_PLAN_INCO_UP",
                    "D_PLAN_INCO_UPO",
                    "D_PLAN_SI",
                    "DIS_T",
                    "DIS_TR",
                    "DKT",
                    "DKTG",
                    "DST",
                    "FLUI_STRU",
                    "POU_FLUI_STRU",
                    "GRILLE_EXCENTRE",
                    "GRILLE_MEMBRANE",
                    "MEMBRANE",
                    "POU_D_E",
                    "POU_D_EM",
                    "POU_D_T",
                    "POU_D_T_GD",
                    "POU_D_TG",
                    "POU_D_TGM",
                    "POU_D_SQUE",
                    "Q4G",
                    "Q4GG",
                    "TUYAU_3M",
                    "TUYAU_6M",
                    "COQUE_SOLIDE",
                    "D_PLAN_HHM",
                    "D_PLAN_HH2M_SI",
                    "D_PLAN_HM",
                    "D_PLAN_HM_SI",
                    "D_PLAN_HM_SI_DIL",
                    "D_PLAN_THM",
                    "D_PLAN_HHMD",
                    "D_PLAN_HH2MD",
                    "D_PLAN_HMD",
                    "D_PLAN_THHD",
                    "D_PLAN_THH2D",
                    "D_PLAN_THVD",
                    "D_PLAN_THH2MD",
                    "D_PLAN_THHMD",
                    "D_PLAN_THMD",
                    "D_PLAN_HHMS",
                    "D_PLAN_HH2MS",
                    "D_PLAN_HH2MS_DIL",
                    "D_PLAN_HMS",
                    "D_PLAN_HMS_DIL",
                    "D_PLAN_THHS",
                    "D_PLAN_THH2S",
                    "D_PLAN_THVS",
                    "D_PLAN_THH2MS",
                    "D_PLAN_THHMS",
                    "D_PLAN_THMS",
                    "D_PLAN_THMS_DIL",
                    "D_PLAN_HS",
                    "D_PLAN_HHD",
                    "D_PLAN_HHS",
                    "D_PLAN_HH2D",
                    "D_PLAN_HH2S",
                    "D_PLAN_2DG",
                    "D_PLAN_DIL",
                    "3D_DIL",
                    "AXIS_THM",
                    "AXIS_HHM",
                    "AXIS_HM",
                    "AXIS_HH2MD",
                    "AXIS_HHMD",
                    "AXIS_HMD",
                    "AXIS_THHD",
                    "AXIS_THH2D",
                    "AXIS_THVD",
                    "AXIS_THHMD",
                    "AXIS_THH2MD",
                    "AXIS_THMD",
                    "AXIS_HH2MS",
                    "AXIS_HHMS",
                    "AXIS_HMS",
                    "AXIS_THHS",
                    "AXIS_THH2S",
                    "AXIS_THVS",
                    "AXIS_THHMS",
                    "AXIS_THH2MS",
                    "AXIS_THMS",
                    "AXIS_HHD",
                    "AXIS_HHS",
                    "AXIS_HH2D",
                    "AXIS_HH2S",
                    "3D_HHM",
                    "3D_HH2M_SI",
                    "3D_HM",
                    "3D_HM_SI",
                    "3D_HM_SI_DIL",
                    "3D_THHM",
                    "3D_THM",
                    "3D_HHMD",
                    "3D_HMD",
                    "3D_THHD",
                    "3D_THVD",
                    "3D_THHMD",
                    "3D_THMD",
                    "3D_HHMS",
                    "3D_HMS",
                    "3D_HMS_DIL",
                    "3D_THHS",
                    "3D_THVS",
                    "3D_THHMS",
                    "3D_THMS",
                    "3D_THMS_DIL",
                    "3D_THH2MD",
                    "3D_THH2MS",
                    "3D_HH2MD",
                    "3D_HH2MS",
                    "3D_HH2MS_DIL",
                    "3D_THH2S",
                    "3D_THH2D",
                    "3D_HS",
                    "3D_HHD",
                    "3D_HHS",
                    "3D_HH2D",
                    "3D_HH2S",
                    "3D_HH2SUDA",
                    "D_PLAN_HH2SUDA",
                    "PLAN_JHMS",
                    "AXIS_JHMS",
                    "3D_HHO",
                    "D_PLAN_HHO",
                    "3D_GRAD_HHO",
                    "D_PLAN_GRAD_HHO",
                    "PLAQ_MITC",
                ),
            ),
            b_formu_hho=BLOC(
                condition="""equal_to('MODELISATION', ('3D_HHO', 'D_PLAN_HHO' ))""",
                fr=tr("HHO formulation"),
                FORMULATION=SIMP(
                    statut="f",
                    typ="TXM",
                    max=1,
                    into=("LINEAIRE", "QUADRATIQUE", "CUBIQUE", "QUARTIQUE"),
                    defaut="LINEAIRE",
                ),
            ),
            b_formu_hho_grad=BLOC(
                condition="""equal_to('MODELISATION', ("D_PLAN_GRAD_HHO", "3D_GRAD_HHO" ))""",
                fr=tr("HHO formulation with GRAD_VARI"),
                FORMULATION=SIMP(
                    statut="f",
                    typ="TXM",
                    max=1,
                    into=("LINEAIRE", "QUADRATIQUE"),
                    defaut="LINEAIRE",
                ),
            ),
            b_formu_fsi=BLOC(
                condition="""equal_to('MODELISATION', ('2D_FLUIDE', '2D_FLUI_ABSO', '2D_FLUI_PESA', '2D_FLUI_STRU','3D_FLUIDE','3D_FLUI_ABSO', 'AXIS_FLUIDE', 'AXIS_FLUI_STRU', 'AXIS_FLUI_ABSO', 'FLUI_STRU'))""",
                fr=tr("FSI formulation"),
                FORMULATION=SIMP(
                    statut="f", typ="TXM", max=1, into=("U_P_PHI", "U_P", "U_PSI"), defaut="U_P_PHI"
                ),
            ),
            b_formu_dil=BLOC(
                condition="""equal_to('MODELISATION', ('D_PLAN_DIL', '3D_DIL', ))""",
                fr=tr("DIL formulation"),
                FORMULATION=SIMP(
                    statut="f", typ="TXM", max=1, into=("DIL", "DIL_INCO"), defaut="DIL"
                ),
            ),
        ),
        b_thermique=BLOC(
            condition="""equal_to("PHENOMENE", 'THERMIQUE')""",
            fr=tr("modélisations thermiques"),
            MODELISATION=SIMP(
                statut="o",
                typ="TXM",
                validators=NoRepeat(),
                max=1,
                into=(
                    "3D",
                    "3D_DIAG",
                    "AXIS",
                    "AXIS_DIAG",
                    "AXIS_FOURIER",
                    "COQUE",
                    "COQUE_AXIS",
                    "COQUE_PLAN",
                    "PLAN",
                    "PLAN_DIAG",
                    "3D_HHO",
                    "PLAN_HHO",
                    "AXIS_HHO",
                    "AXIS_SECH",
                    "3D_SECH",
                    "AXIS_SECH_DIAG",
                    "3D_SECH_DIAG",
                ),
            ),
            b_formu_hho=BLOC(
                condition="""equal_to('MODELISATION', ('3D_HHO', 'PLAN_HHO', 'AXIS_HHO'))""",
                fr=tr("HHO formulation"),
                FORMULATION=SIMP(
                    statut="f",
                    typ="TXM",
                    max=1,
                    into=("CONSTANTE", "LINEAIRE", "QUADRATIQUE", "CUBIQUE", "QUARTIQUE"),
                    defaut="LINEAIRE",
                ),
            ),
        ),
        b_acoustique=BLOC(
            condition="""equal_to("PHENOMENE", 'ACOUSTIQUE')""",
            fr=tr("modélisations acoustiques"),
            MODELISATION=SIMP(
                statut="o",
                typ="TXM",
                validators=NoRepeat(),
                max=1,
                into=(
                    "3D",
                    "PLAN",
                    "3D_ABSO",
                    "PLAN_ABSO",
                ),
            ),
        ),
    ),
    DISTRIBUTION=FACT(
        statut="d",
        METHODE=SIMP(
            statut="f",
            typ="TXM",
            defaut="SOUS_DOMAINE",
            into=("MAIL_CONTIGU", "MAIL_DISPERSE", "CENTRALISE", "GROUP_ELEM", "SOUS_DOMAINE"),
        ),
        b_dist_maille=BLOC(
            condition="""is_in("METHODE", ('MAIL_DISPERSE','MAIL_CONTIGU'))""",
            CHARGE_PROC0_MA=SIMP(statut="f", typ="I", defaut=100, val_min=0, val_max=100),
        ),
        b_partition=BLOC(
            condition="""equal_to("METHODE",'SOUS_DOMAINE' )""",
            NB_SOUS_DOMAINE=SIMP(statut="f", typ="I"),  # par defaut : le nombre de processeurs
            PARTITIONNEUR=SIMP(statut="f", typ="TXM", into=("METIS", "SCOTCH"), defaut="METIS"),
        ),
    ),
    VERI_JACOBIEN=SIMP(
        statut="f",
        typ="TXM",
        into=("OUI", "NON"),
        defaut="OUI",
        fr=tr("Vérification de la forme des mailles (jacobiens tous de meme signe)."),
    ),
    VERI_NORM_IFS=SIMP(
        statut="f",
        typ="TXM",
        into=("OUI", "NON"),
        defaut="OUI",
        fr=tr("Vérification de l'orientation des normales pour l'IFS"),
    ),
    VERI_FORMULATION_IFS=SIMP(
        statut="f",
        typ="TXM",
        into=("OUI", "NON"),
        defaut="OUI",
        fr=tr("Vérification de la cohérent de la formulation pour l'IFS"),
    ),
    VERI_PLAN=SIMP(
        statut="f",
        typ="TXM",
        into=("OUI", "NON"),
        defaut="OUI",
        fr=tr("Vérification de la planéité des éléments"),
    ),
    translation={
        "AFFE_MODELE": "Assign finite element",
        "AFFE": "Finite element assignement",
        "AFFE_SOUS_STRUC": "Substructures assignement",
        "VERI_JACOBIEN": "Jacobian check",
        "DISTRIBUTION": "MPI distribution",
        "TOUT": "Everywhere",
    },
)
