# coding=utf-8
# --------------------------------------------------------------------
# Copyright (C) 1991 - 2025 - EDF R&D - www.code-aster.org
# This file is part of code_aster.
#
# code_aster is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# code_aster is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with code_aster.  If not, see <http://www.gnu.org/licenses/>.
# --------------------------------------------------------------------

import os
import os.path as osp
import re
import shutil
from functools import partial

from waflib import Configure, Errors, Logs, Task, TaskGen, Utils


def options(self):
    pass


def configure(self):
    if not self.env["PYTHON"]:
        self.fatal("load python tool first")
    self.env.LIBPATH_ASTERGC = self.env.ASTERLIBDIR
    self.env.PYPATH_ASTERGC = self.env.ASTERLIBDIR


def build(self):
    env = self.all_envs[self.variant]
    get_srcs = self.path.get_src().ant_glob

    use = ["MATH"]
    if self.env.BUILD_OPENMP:
        use.append("OPENMP")

    srcF90 = get_srcs("**/*.F90")
    self(
        features="fc fcshlib",
        name="asterfortgc",
        target="AsterGC",
        source=srcF90,
        use=use,
        env=env.derive(),
        install_path=env.LIBPATH_ASTERGC,
    )
