# coding=utf-8
# --------------------------------------------------------------------
# Copyright (C) 1991 - 2025 - EDF R&D - www.code-aster.org
# This file is part of code_aster.
#
# code_aster is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# code_aster is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with code_aster.  If not, see <http://www.gnu.org/licenses/>.
# --------------------------------------------------------------------

import os
import os.path as osp
import sys
from pathlib import Path

from waflib import Configure, Logs, TaskGen, Utils, Build


def options(self):
    # already done by waftools/parallel.py: self.load("compiler_c")
    group = self.get_option_group("code_aster options")
    group.add_option(
        "-e",
        "--build-executable",
        dest="embed_aster",
        default=False,
        action="store_true",
        help="build aster as an executable: it is an alias for --embed-aster",
    )
    group.add_option(
        "--embed-aster",
        dest="embed_aster",
        default=True,
        action="store_true",
        help="embed all aster components within a python interpreter",
    )
    group.add_option(
        "--shared-aster",
        dest="embed_aster",
        default=True,
        action="store_false",
        help="build each aster component as a shared python module",
    )


def configure(self):
    # already done by waftools/parallel.py: self.load("compiler_c")
    # preserve symbols in the dyn table for stdcalls
    if self.env.ASTER_PLATFORM_MINGW:
        self.add_linkflags(["-Wl,--export-all-symbols"])
    elif sys.platform != "darwin":
        self.add_linkflags("-Wl,--export-dynamic")
    else:
        # '--export-dynamic' is '-export_dynamic' in OS X linker
        # http://stackoverflow.com/questions/21279036/what-is-clangs-equivalent-to-rdynamic-gcc-flag
        self.add_linkflags("-Wl,-export_dynamic")

    # prefer memory usage over speed
    self.add_linkflags("-Wl,--no-keep-memory")
    # this option removes the warning about executable stack because of nested functions
    # https://sourceware.org/bugzilla/show_bug.cgi?id=29072
    self.add_linkflags("-Wl,--no-warn-execstack")

    self.add_linkflags("-Wl,--no-as-needed", dest="LINKFLAGS_LIBASTER")
    self.add_linkflags("-Wl,-flto=auto", dest="LINKFLAGS")
    # seems incompatible with subroutines like zerofr that takes function as argument (test ssnv168f)
    # self.add_linkflags("-Wl,-z,noexecstack", dest="LINKFLAGS")

    incpath = osp.join(self.path.get_src().abspath(), "include")
    self.env.append_value("INCLUDES_BIBC", incpath)

    if self.env.CC_IS_INTEL:
        self.add_linkflags("-nofor-main", dest="LINKFLAGS_fcprogram")
    self.check_c_compiler_flags()

    if self.env.ASTER_PLATFORM_MSYS2:
        self.check_cc(lib="gfortran", uselib_store="GFORTRAN")
        self.check_cc(lib="dbghelp", uselib_store="DBGHELP")


@Configure.conf
def check_bibc_depends(self):
    """check dependencies of bibc"""
    # never in static
    self.check_cc(uselib_store="SYS", lib="dl")


@Configure.conf
def add_linkflags(self, linkflags, dest="LINKFLAGS"):
    """Add linkflags if they are supported by the active compiler."""
    if not linkflags:
        return
    linkflags = Utils.to_list(linkflags)

    self.start_msg("Checking for linkflags")
    supportedFlags = []
    for flags in linkflags:
        flags = Utils.to_list(flags)
        if self.check_cxx(linkflags=["-Werror"] + flags, mandatory=False):
            supportedFlags += flags
    self.end_msg(" ".join(supportedFlags))
    self.env.append_unique(dest, supportedFlags)


PYMAIN = "supervis/python.c"


def build(self):
    # The build is splitted in 3 stages:
    # - compilation of C source files
    # - build of the shared lib (libaster)
    get_srcs = self.path.get_src().ant_glob
    env = self.all_envs[self.variant]

    build_libbibc(self, env)
    build_libaster(self, env)

    self.add_group()
    # install headers
    self.install_files(env.ASTERINCLUDEDIR, get_srcs("include/*.h"))
    # install generated headers (C + fortran)
    bld = self.path.get_bld().parent
    config_includes = bld.ant_glob("aster*_config.h", quiet=True)
    self.install_files(env.ASTERINCLUDEDIR, config_includes)


@TaskGen.extension(".h")
def process_h(self, node):
    pass


def post_install_links(ctx):
    if not ctx.cmd.startswith("install"):
        return

    python_install_path = ctx.env.SPDIR if ctx.env.SPDIR else ctx.env.ASTERLIBDIR
    asterlibdir = Path(python_install_path)

    extlib = "so"
    mods = ["aster", "aster_core", "aster_fonctions"]
    libaster = "libaster.so"
    if ctx.env.ASTER_PLATFORM_MINGW:
        extlib = "pyd"
        mods.extend(["libaster", "libAsterGC"])
        libaster = "aster.dll"

    libaster_path = asterlibdir / libaster
    if not libaster_path.exists():
        Logs.warn(f"{libaster_path} not found")
        return

    for linkname in (f"{mod}.{extlib}" for mod in mods):
        linkpath = asterlibdir / linkname

        if linkpath.exists():
            linkpath.unlink()
        if ctx.env.ASTER_PLATFORM_MSYS2:
            os.link(libaster_path, linkpath)
            Logs.info(f"Created hardlink: {linkpath}")
        else:
            os.symlink(libaster_path.name, linkpath)
            Logs.info(f"Created symlink: {linkpath}")


def build_libbibc(self, env):
    use = [
        "PYEXT",
        "NUMPY",
        "BIBCXX",
        "HDF5",
        "MED",
        "METIS",
        "PARMETIS",
        # "GKLIB",
        "SCOTCH",
        "PETSC",
        "ASAN",
    ]
    get_srcs = self.path.get_src().ant_glob

    # Determine install paths - DLLs go to BINDIR on Windows, libs stay in LIBDIR
    if self.env.ASTER_PLATFORM_MSVC64:
        lib_install_path = env.ASTERBINDIR
    else:
        lib_install_path = env.ASTERLIBDIR

    # compile *.c
    self(
        features=("c cstlib" if self.env.ASTER_PLATFORM_MINGW else "c cshlib"),
        name="asterbibc",
        source=get_srcs("**/*.c", excl=[PYMAIN]),
        target="bibc",
        rpath="$ORIGIN",
        defines="",
        use=use,
        env=env.derive(),
        install_path=lib_install_path,
    )


def build_libaster(self, env):
    use = [
        "LIBASTER",
        "ASAN",
        "asterbibfor",
        "asterbibfor_ext",
        "asterbibc",
        "asterbibcxx",
        "astergc",
    ]
    if self.env.ASTER_PLATFORM_MSYS2:
        use.append("GFORTRAN")
        use.append("DBGHELP")
    if env.BUILD_MFRONT:
        use.append("astermfront")

    # Determine install path for aster.dll
    # On MSVC, DLLs go to BINDIR, on other platforms to SPDIR/ASTERLIBDIR
    python_install_path = env.SPDIR if env.SPDIR else env.ASTERLIBDIR
    if self.env.ASTER_PLATFORM_MSVC64:
        install_path = env.ASTERBINDIR
    else:
        install_path = python_install_path

    # {bibfor, bibc, bibcxx}/*.o
    if self.env.ASTER_PLATFORM_MINGW:
        # fix circular dependencies between bibc.a and bibfor.a
        env = env.derive()
        env.detach()
        env.append_value("STLIB_MARKER", "-Wl,--start-group")
        env.append_value("SHLIB_MARKER", "-Wl,--end-group")
    self(
        features="cxx cxxshlib",
        name="asterlib",
        target="aster",
        rpath="$ORIGIN",
        source=PYMAIN,
        defines="_MAIN_=_unused_main_",  #'ASTER_WITHOUT_PYMOD',
        env=env.derive(),
        use=use,
        install_path=install_path,
    )

    self.add_post_fun(post_install_links)


@Configure.conf
def check_c_compiler_flags(self):
    self.check_c_compiler_options("-fPIC")
    # needs more tests (size and build time)
    # self.check_c_compiler_options("-fno-lto")
    self.start_msg("C compiler flags")
    self.end_msg(self.env["CFLAGS"])


@Configure.conf
def check_c_compiler_options(self, options):
    """Check C compiler options"""
    if type(options) not in (list, tuple):
        options = [options]
    self.start_msg("Checking for C option")
    if self.check_cc(cflags=options, mandatory=False):
        self.env.append_unique("CFLAGS", options)
        self.end_msg("yes (%s)" % " ".join(options))
    else:
        self.end_msg("no (%s)" % " ".join(options), "YELLOW")


@Configure.conf
def check_optimization_cflags(self):
    self.setenv("debug")
    self.start_msg("Setting C debug flags")
    self.remove_optflags("CFLAGS")
    flags = ["-g", "-O0"] + Utils.to_list(self.env["CFLAGS_ASTER_DEBUG"])
    if self.options.enable_coverage:
        flags.append("--coverage")
        self.add_linkflags("--coverage")
    self.env.append_unique("CFLAGS", flags)
    self.end_msg(flags)

    self.setenv("release")
    self.start_msg("Setting C optimization flags")
    flags = ["-O2"]
    self.env.append_unique("CFLAGS", flags)
    self.end_msg(flags)


@Configure.conf
def check_asan(self):
    if not self.options.enable_asan:
        return
    # there is only one profile.sh, so the flags must also be set for release
    # setup compilation flags
    flags = ["-fsanitize=address,undefined", "-fno-omit-frame-pointer"]
    for var in ("CFLAGS", "CXXFLAGS", "FCFLAGS"):
        self.start_msg(f"Setting AddressSanitizer {var}")
        self.env.append_unique(f"{var}_ASAN", flags)
        self.end_msg(flags)
    self.add_linkflags(flags, dest="LINKFLAGS_ASAN")

    # setup runtime variables
    self.find_program("ldd")
    libasan = self.where_is_shlib(lib="asan")
    self.env["ASAN_PRELOAD"] = [libasan]
    self.env.append_unique("CONFIG_ENV_LD_PRELOAD", self.env["ASAN_PRELOAD"])
    self.start_msg("Setting default ASAN_OPTIONS")
    # to use the same defaults in catalo
    self.env["ASAN_DEFAULT_OPTIONS"] = defaults = "detect_odr_violation=1,detect_leaks=0"
    opts = os.environ.get("ASAN_OPTIONS", f"${{ASAN_OPTIONS:-{defaults}}}")
    self.env["CONFIG_ENV_ASAN_OPTIONS"] = opts
    self.end_msg(self.env["CONFIG_ENV_ASAN_OPTIONS"])
