name: ci-code-aster-build

# bump 1
on:
  workflow_dispatch:
  push:
    branches:
      - win-support
#    - donotrun

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: '1'

      - uses: ./.github/actions/install-intel-fortran
        if: ${{ runner.os == 'Windows' }}
        with:
          version: 2025.0.0
          activate: false

      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.36.0
          cache: true

      - name: Build Code_Aster
        shell: cmd
        run: |
          pixi run build

      - name: If failed build, upload log
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: BuildLog-${{ runner.os }}-${{ github.run_id }}
          path: ${{ github.workspace }}/build

      - name: Install Code_Aster
        run: |
          pixi run install

      - name: Test Code_Aster
        run: |
          pixi run test

      - name: Save Run directory to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TestResults-${{ runner.os }}-${{ github.run_id }}
          path: ${{ github.workspace }}/temp
