name: ci-condadev-build

on:
  workflow_dispatch:
  push:
    branches:
      - win-support

permissions:
  contents: read

jobs:
  build-aster:
    name: Build Code_Aster (Windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: '1'

      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: v0.62.2
          environments: condadev
          activate-environment: condadev
          cache: false

      - name: Build Code_Aster
        shell: bash
        run: |
          pixi run -e condadev cbuild-dev --skip-existing=all

      - name: If failed build, upload log
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: BuildLog-condadev-${{ github.run_id }}
          path: ${{ github.workspace }}/output/bld/rattler-build_code-aster_*/work/build
